### ISSUE TITLE
Bug: Non-Blocking frame handling of Video Files in CamGear Class

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#20]
## Bug Insights
Currently, CamGear(or common VidGear Class) uses separate threads to process frames from the given source at certain high speed one after another, let's say, 50fps(_50 frames per second_). Now for a video source, imagine we are performing a heavy computational task where the frames are being processed at 5fps only. Under these conditions due to multi-threaded frame capturing, CamGear will keep on cycling frames from the source at 50fps in the background even while no one is requesting for them and thereby finally end up **returning a `NoneType` frame at the output if video file(_as source_) is of fixed length. This erroneous behavior also leads to the wrong frame being processed at any given instance and another undesired behavior called _Frame Skipping_**

### Affected VideoCapture Streams::warning:
* **_This bug is present in any video stream of fixed length including network streams_**
* **_This bug doesn't affect camera (H.W) devices_**

### Code to Reproduce Bug:

This code will call sleep function for a duration of 2secs at each loop cycle to imitate a heavy  computation task being performed and counts frame number that is being processed:

```python
from vidgear.gears import CamGear
import cv2
import time

stream = CamGear(source='test.mp4').start() #Open any video file stream of fixed length

# infinite loop
frame_num = 0
while True:
	
	frame = stream.read()
	# read frames

	# check if frame is None
	if frame is None:
		#if True break the infinite loop
                print(frame_num)
		break
	
	# Sleep for 1 seconds (imitating a heavy computational task)
	time.sleep(2)
	   
	# Show output window
	cv2.imshow("Output Frame", frame)

	key = cv2.waitKey(1) & 0xFF
	# check for 'q' key-press
	if key == ord("q"):
		#if 'q' key-pressed break out
		break
        frame_num+=1
cv2.destroyAllWindows()
# close output window

stream.stop()
# safely close video stream
```

### Current Behavior(Output)
Due to the above-mentioned bug, when this algorithm is run, it will exit immediately without processing each frame or skipped frames will visible depending upon the length of the input video. The final `frame_num` value will be around `0~10` (when a 20-120 sec video is used),  which is far less than in comparison to actual numbers.

### TODO
- [x] Implement a **Blocking Mode** in CamGear Class with a threaded queue
- [x] Use `collections.deque()` for performance consideration
- [x] Add a test for this Mode
- [x] Fix Bugs and robust testing of this implementation.

**Comment by abhiTronix** [comment]
## Purposed Fix

PR #21 Introduces **Threaded Queue Mode for CamGear Class(will work with VideoGear CommonClass too), that enables Blocking use of the source in Fixed-Length Video Streams**. This Mode is enabled by default for any Videocapture stream(_except any connected Camera/H.W device_s).

### Manually DIsabling/Enabling of Threaded Queue Mode:
To manually alter this mode, CamGear Class now provides` THREADED_QUEUE_MODE` user-defined flag. This flag can be easily set to **True**(_to enable_) or unset to **False**(_to disable_) this mode by passing this parameter to [`**options`](https://github.com/abhiTronix/vidgear/wiki/CamGear-Class#parameters-and-attributes-wrench) dict of CamGear class as follows:
```python
options = {'THREADED_QUEUE_MODE': True} #to enable Threaded Queue Mode
```
### Features:
- Enables Blocking, Sequential and Threaded LIFO Frame Handling.
- It Sequentially adds and releases frames to/from deque and handles the overflow of this queue.
- It utilizes deques that support thread-safe, memory efficient appends and pops from either side of the deque with approximately the same O(1) performance in either direction.
- Requires less RAM at due to buffered frames in the deque.

### Drawbacks:

-    Direct Colorspace conversion/manipulation may result in delayed/incorrect results, only when this mode is activated
-    Cannot be applied to Camera Feed/H.W. Devices.

**Comment by abhiTronix** [comment]
**Successfully Fixed in 6b649eb**
