### ISSUE TITLE
Remove range from publication year in Copyright Notice

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#238]
## Description

The vidgear's license contains publication date range in copyright notice which is not ideal for a Open-Source Licenses. It is recommended in  [US copyright notices defined by Title 17, Chapter 4(Visually perceptible copies)](https://www.copyright.gov/title17/92chap4.html) to put only year date of first publication of the compilation or derivative work.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:  v0.2.2
* Branch:  Development

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/11f7dadc67874bf38808853b0c69821eddb2fd64**
