### ISSUE TITLE
Enhancement: Multithreaded Live Screen Cast support in vidgear

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#26]
# Multithreaded Live Screen Cast
## Introduction:
A screencast is a digital recording of computer screen output, also known as a video screen capture. The term screencast compares with the related term screenshot; whereas screenshot generates a single picture of a computer screen, a screencast is essentially a movie of the changes over time that a user sees on a computer screen.

### [Python MSS](https://github.com/BoboTiG/python-mss):
MSS stands for Multiple Screen Shots, is an ultra-fast cross-platform multiple screenshots module in pure python using ctypes. With MSS we can easily define an area on the computer screen or an open window to record the live screen.

## Goal
Our goal is to implement live Screen Cast support in vidgear by implementing a high-level wrapper around  [Python MSS](https://github.com/BoboTiG/python-mss) at the expense of low latency in python.

## TODO
- [x] Implement Live Screen Cast support in vidgear
- [x] Prepare a Multi-Threaded wrapper around Python-MSS
- [x] Create new  `ScreenGear` class from scratch to implement this feature
- [x] Make `ScreenGear` compatible with existing vidgear Classes.
- [x] Must provide higher framerate at low latency with fewer resources
- [x] Optimize overall performance
- [x] Fix related bugs

**Comment by abhiTronix** [comment]
## Bug in Python-mss

While experimenting with [Python-mss](https://github.com/BoboTiG/python-mss) library. I discovered Hugely Framedrop and latency at the ScreenGear output. On further investigating this issue, I came across this [issue](https://github.com/BoboTiG/python-mss/issues/19#issue-242604557). 

### Bug Summary:

While displaying OpenCV/Numpy to record the screen using Python-mss, The frames are getting delayed with time(exponentially.
This results in the display window not responding due to lack of resources. 

This bug is significant when opencv output window `cv2.imshow('output', frame)` is used inside loop. 

### Code to reproduce this Bug:

```python3

import cv2
import mss
import numpy


with mss.mss() as sct:
    # select current monitor
    monitor = sct.monitors[1]

    while "Screen capturing":
        last_time = time.time()

        # Get raw pixels from the screen, save it to a Numpy array
        img = numpy.array(sct.grab(monitor))

        # Display the picture
        cv2.imshow("OpenCV/Numpy normal", img)

        # Display the picture in grayscale
        # cv2.imshow('OpenCV/Numpy grayscale',
        #            cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY))

        print("fps: {}".format(1 / (time.time() - last_time)))

        # Press "q" to quit
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
cv2.destroyAllWindows()

```

The framerate `fps` drops exponentially to zero with this example code, hence resulting in this bug.

**Comment by abhiTronix** [comment]
Successfully merged in commit 7902a8d3e0208e5a39275c5a517c1dfe098ce95d
