### ISSUE TITLE
[Proposal]: Dropping support for Python 3.7.x legacy

### ISSUE THREAD

**Issue by abhiTronix** [abhiTronix/vidgear#369]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

### Describe your Idea

As of 05 Jun 2023, Python 3.7.x legacy has reached its end of support, resulting in the discontinuation of security updates and general widespread availability: https://endoflife.date/python

### Use Cases

Consequently, this issue is to inform you that the `3.7.x` legacy will no longer be supported in the upcoming version `v0.3.2` of vidgear. This implies that starting from version `v0.3.2` and onwards, vidgear will no longer function properly on `3.7.x` legacy, and any associated bugs pertaining to this legacy version will not be addressed in future releases.

### Any other Relevant Information?

https://endoflife.date/python

**Comment by abhiTronix** [comment]
Additionally, the support for python [3.11](https://docs.python.org/3.10/whatsnew/3.10.html) will be officially added in this version. Thank you. 🎉

**Comment by abhiTronix** [comment]
**Successfully replaced python `3.7.x` with `3.11.x` legacy version in commit  https://github.com/abhiTronix/vidgear/commit/1628685b25fb39a0b59c4af0fd899eedb797b02c 🎉**
