### ISSUE TITLE
[Proposal]: Update documentation with a containerized application example (most likely the "help/" section)

### ISSUE THREAD

**Issue by alessio-locatelli** [abhiTronix/vidgear#421]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) and found nothing related to my idea.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and it doesn't mention anything about my idea.
- [X] To my best knowledge, my idea wouldn't break something for other users.

#### To-do:
- [ ] In the [docs/help/camgear_ex.md](https://github.com/abhiTronix/vidgear/blob/5f4127b06b9e3e53f9a8d4191609ac41a3b82ad4/docs/help/camgear_ex.md?plain=1#L168) add a link to the  [`ReconnectingCamGear`](https://github.com/alessio-locatelli/vidgear-docker-application-example/blob/main/app/reconnecting_cam_gear.py#L13) because the second example is battle-tested and can be used as is. 
- [ ] Add a link to the [vidgear containerized demo project](https://github.com/alessio-locatelli/vidgear-docker-application-example/) somewhere in the documentation. Add a small note that the code provided can be used as a starting point for beginners, or if someone doubts that a bug is related to the system packages, to compare the behaviour inside a Docker container. 

### Use Cases

- A consistent, reproducible environment that people can use to verify possible bugs or try out the code without being overwhelmed by system-specific problems like different versions of `ffmpeg` and other system packages. 
- An additional example for beginners.

**Comment by abhiTronix** [comment]
Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/pull/438/commits/a9ba7d768838dc0c3854efd6922bdcf4d75aab41
